// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxtgdvwasdbrbyiiyrhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dGdkdndhc2RicmJ5aWl5cmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyMjc0MDksImV4cCI6MjA1MjgwMzQwOX0.A-_lOYasfjVWOsLw8WsVcjAcvjClwau6J_y_WeSUp0s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);